spec:
  templates:
    - name: gabor-batch
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: run-gabor-batch
            template: run-gabor-batch
            arguments:
              parameters:
                - name: job_id
                  value: "{{item}}"
            withSequence:
              count: "30"
    - name: run-gabor-batch
      inputs:
        parameters:
          - name: job_id
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: mpisman/birds_p0:latest
        command:
          - python
          - main.py
        args:
          - --job_id={{inputs.parameters.job_id}}
          - --mongodb_url=mongodb://root:password@mongodb:27017
        resources: {}
      podSpecPatch: |
        {
          "affinity": {
            "podAntiAffinity": {
              "preferredDuringSchedulingIgnoredDuringExecution": [
                {
                  "weight": 100,
                  "podAffinityTerm": {
                    "labelSelector": {
                      "matchExpressions": [
                        {
                          "key": "workflows.argoproj.io/workflow",
                          "operator": "In",
                          "values": ["{{workflow.name}}"]
                        }
                      ]
                    },
                    "topologyKey": "kubernetes.io/hostname"
                  }
                }
              ]
            }
          }
        }
  entrypoint: gabor-batch
  arguments: {}
  serviceAccountName: argo-workflow
  parallelism: 30
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnPodSuccess
